### ISSUE TITLE
Update to Gradle 9.1

### ISSUE THREAD

**Issue by schreiaj** [CDCgov/prime-simplereport#9220]
## What needs to be done

[PR #9161 ](https://github.com/CDCgov/prime-simplereport/pull/9161) attempts to update to Gradle 9.1 this results in a few java compilation errors with the lombok annotation processor (ie it doesn't compile) It also highlighted a few potential JPA relationship errors but that appears to be a red herring. 

## Why it needs to be done

If we need to update to Gradle 9.1, we need to make annotation processing work correctly or the code simply won't compile

## Acceptance Criteria

SR builds using Gradle 9.1 and passes all existing tests

-

## Technical Notes

Some details - it appears that Lombok was either not running correctly _or_ the generated classfiles were not being added. Disabling JPA Validation with 

```
tasks.withType(JavaCompile) {
    options.annotationProcessorPath = configurations.annotationProcessor
    options.compilerArgs += [
        '-Aorg.hibernate.jpamodelgen.validation.usage=DISABLED'
    ]
}
```

Didn't resolve issues which is why I assumed the JPA validation errors were a red herring. It is possible updating lombok version could resolve this but it seemed beyond the scope of a simple dependabot ticket.
